-- Create team_members table
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  linkedin_url TEXT,
  twitter_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

-- Allow public read access (anyone can view team members)
CREATE POLICY "Allow public read access"
  ON team_members
  FOR SELECT
  USING (true);

-- Allow authenticated insert
CREATE POLICY "Allow insert"
  ON team_members
  FOR INSERT
  WITH CHECK (true);

-- Allow authenticated update
CREATE POLICY "Allow update"
  ON team_members
  FOR UPDATE
  USING (true);

-- Allow authenticated delete
CREATE POLICY "Allow delete"
  ON team_members
  FOR DELETE
  USING (true);

-- ============================================
-- Storage bucket for team member images
-- ============================================
-- Run this in the Supabase SQL Editor as well.
-- This creates a public bucket called 'team-images'.

INSERT INTO storage.buckets (id, name, public)
VALUES ('team-images', 'team-images', true)
ON CONFLICT (id) DO NOTHING;

-- Allow public read access to team images
CREATE POLICY "Public read team images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'team-images');

-- Allow anyone to upload team images (for admin use)
CREATE POLICY "Allow upload team images"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'team-images');

-- Allow anyone to update team images
CREATE POLICY "Allow update team images"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'team-images');

-- Allow anyone to delete team images
CREATE POLICY "Allow delete team images"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'team-images');
