-- Create team_members table
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  linkedin_url TEXT,
  twitter_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

-- Allow public read access (anyone can view team members)
CREATE POLICY "Allow public read access"
  ON team_members
  FOR SELECT
  USING (true);

-- Allow authenticated insert
CREATE POLICY "Allow insert"
  ON team_members
  FOR INSERT
  WITH CHECK (true);

-- Allow authenticated update
CREATE POLICY "Allow update"
  ON team_members
  FOR UPDATE
  USING (true);

-- Allow authenticated delete
CREATE POLICY "Allow delete"
  ON team_members
  FOR DELETE
  USING (true);
