-- Create a table for Team Members
create table if not exists team_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text not null,
  description text,
  image_url text,
  linkedin_url text,
  twitter_url text
);

-- Enable Row Level Security (RLS)
alter table team_members enable row level security;

-- Create policies for Team Members
-- Allow everyone to view team members
create policy "Public team members are viewable by everyone"
  on team_members for select
  using ( true );

-- Allow authenticated users (admins) to insert, update, and delete
create policy "Admins can insert team members"
  on team_members for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update team members"
  on team_members for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete team members"
  on team_members for delete
  using ( auth.role() = 'authenticated' );

-- Create a table for Page Visits (Simple Analytics)
create table if not exists page_visits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  path text not null,
  user_agent text
);

-- Enable RLS
alter table page_visits enable row level security;

-- Allow everyone to log a visit (insert)
create policy "Everyone can insert page visits"
  on page_visits for insert
  with check ( true );

-- Allow only admins to view visits
create policy "Admins can view page visits"
  on page_visits for select
  using ( auth.role() = 'authenticated' );
